apiVersion: v1
entries:
  stable-diffusion:
  - apiVersion: v2
    appVersion: 1.5.0
    created: "2023-08-19T00:45:24.295612+08:00"
    description: Packaged Stable Diffusion with a companion UI and automatic model
      retrieval
    digest: 7b86b72eaa6c017d31941abd05a59b87b5814a9505da4592eba78fb49e0adbcb
    name: stable-diffusion
    type: application
    urls:
    - charts/stable-diffusion-1.0.18.tgz
    version: 1.0.18
generated: "2023-08-19T00:45:24.295238+08:00"
