apiVersion: v2
name: ibytechaos
description: Certificate management chart for ibytechaos.com with traefik and cert-manager integration

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: "1.0.5"

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.0"

keywords:
  - certificate
  - cert-manager
  - traefik
  - https
  - wildcard

maintainers:
  - name: ibytechaos
    url: https://ibytechaos.com

home: https://ibytechaos.com
sources:
  - https://github.com/cert-manager/cert-manager
  - https://github.com/traefik/traefik