# Default values for ibytechaos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# ClusterIssuer configuration
clusterIssuer:
  # Whether to create a ClusterIssuer
  create: true
  # Name of the ClusterIssuer
  name: "ibytechaos-issuer"
  # ACME server URL (Let's Encrypt production by default)
  server: "https://acme-v02.api.letsencrypt.org/directory"
  # Contact email for certificate notifications
  email: "wu.zhi.peng@outlook.com"
  # Private key secret name for ACME account
  privateKeySecretRef: "ibytechaos-issuer-key"
  # ACME challenge solver configuration
  solvers:
    # DNS01 solver for wildcard certificates (Tencent Cloud)
    - dns01:
        webhook:
          groupName: acme.cert-manager.io
          solverName: dnspod
          config:
            region: "{{ .Values.tencentCloud.region }}"
            secretId:
              secretName: "{{ .Values.tencentCloud.secretName }}"
              key: "secret-id"
            secretKey:
              secretName: "{{ .Values.tencentCloud.secretName }}"
              key: "secret-key"
      # For wildcard certificates
      selector:
        dnsNames:
        - "*.ibytechaos.com"
        - "ibytechaos.com"
    # HTTP01 solver for apex domain
    - http01:
        ingress:
          class: traefik
      selector:
        dnsNames:
        - "ibytechaos.com"

# Certificate configuration
certificate:
  # Whether to create a Certificate resource
  create: true
  # Certificate name
  name: "ibytechaos-tls"
  # Certificate secret name where TLS cert will be stored
  secretName: "ibytechaos-tls-secret"
  # Certificate issuer reference
  issuerRef:
    name: "ibytechaos-issuer"
    kind: ClusterIssuer
    group: cert-manager.io
  # Common name for the certificate
  commonName: "*.ibytechaos.com"
  # DNS names covered by this certificate (wildcard + root domain only)
  dnsNames:
    - "*.ibytechaos.com"
    - "ibytechaos.com"
  # Certificate duration (90 days by default)
  duration: "2160h" # 90 days
  # Certificate renewal time (30 days before expiry)
  renewBefore: "720h" # 30 days
  # Private key rotation policy (Never, Always)
  rotationPolicy: "Never"
  # Subject configuration
  subject:
    organizations:
      - "IByteChaos"
    countries:
      - "US"
    organizationalUnits:
      - "IT Department"
    localities:
      - "San Francisco"
    provinces:
      - "CA"

# Tencent Cloud DNS configuration
tencentCloud:
  # Tencent Cloud region (e.g., ap-beijing, ap-shanghai, ap-guangzhou)
  region: "ap-beijing"
  # Secret name containing Tencent Cloud API credentials (in cert-manager namespace)
  secretName: "tencent-secret"
  # Whether to create the secret (set to false if you create it manually)
  createSecret: false
  # Tencent Cloud SecretId (only used if createSecret is true)
  secretId: ""
  # Tencent Cloud SecretKey (only used if createSecret is true)
  secretKey: ""
  # Secret namespace (usually cert-manager)
  secretNamespace: "cert-manager"

# Global settings
global:
  # Domain name
  domain: "ibytechaos.com"
  # Wildcard domain
  wildcardDomain: "*.ibytechaos.com"

# Namespace configuration
namespace:
  # Create namespace if it doesn't exist
  create: false
  # Namespace name (if empty, uses release namespace)
  name: ""

# Additional labels to add to all resources
labels: {}

# Additional annotations to add to all resources  
annotations: {}