{{- if .Values.tencentCloud.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tencentCloud.secretName }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "ibytechaos.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  # Base64 encoded Tencent Cloud SecretId
  secret-id: {{ .Values.tencentCloud.secretId | b64enc | quote }}
  # Base64 encoded Tencent Cloud SecretKey
  secret-key: {{ .Values.tencentCloud.secretKey | b64enc | quote }}
{{- end }}